spring.application.name=ingressos

spring.datasource.url=jdbc:mariadb://localhost:3306/venda_ingressos
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# versão mais nova no springinicializer e precisou usar esse dialeto
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect